on: workflow_dispatch
  
jobs:
  build:
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.13

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile --add-data=int.txt:. --add-data=czas.txt:. --window --hidden-import='PIL._tkinter_finder' main.py 
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
